### ISSUE TITLE
大神能否适配一下CR1000A

### ISSUE THREAD

**Issue by kinglove1990** [LiBwrt/openwrt-6.x#54]
国外有支持的，自己编译貌似没有NSS，恳请大佬适配
https://github.com/tsg2k2/openwrt

硬件参数：
CPU: IPQ8072A
RAM: 2GB
EMMC: 4GB
Switch Chip: RTL9093
10G Chip: 2 x AQC113C
2.5G Chip: RTL8221B
Radio 1: QCN5054
Radio 2: QCN6024 
Radio 3: QCN9024

**Comment by kinglove1990** [comment]
搞定了

**Comment by kinglove1990** [comment]
已搞定

**Comment by faninx** [comment]
@kinglove1990 你那个CR1000A固件可以开320MHz吗？

> 已搞定

**Comment by kinglove1990** [comment]
> [@kinglove1990](https://github.com/kinglove1990) 你那个CR1000A固件可以开320MHz吗？
> 
> > 已搞定

9074/9024有320mhz的驱动？我不清楚啊

**Comment by faninx** [comment]
> > [@kinglove1990](https://github.com/kinglove1990) 你那个CR1000A固件可以开320MHz吗？
> > > 已搞定
> 
> 9074/9024有320mhz的驱动？我不清楚啊

哦哦，我记混了，Sorry Sorry
