### ISSUE TITLE
编译最新的6.12版本出错，求助~

### ISSUE THREAD

**Issue by jxph1123** [LiBwrt/openwrt-6.x#59]
求助~~

```
make[4]: Entering directory '/home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.12.4'
  CC [M]  /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.o
/home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.c: In function 'nss_tunipip6_stats_read':
/home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.c:47:15: error: implicit declaration of function 'vzalloc'; did you mean 'kzalloc'? [-Werror=implicit-function-declaration]
   47 |         buf = vzalloc(size);
      |               ^~~~~~~
      |               kzalloc
/home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.c:47:13: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
   47 |         buf = vzalloc(size);
      |             ^
/home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.c:82:9: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
   82 |         vfree(buf);
      |         ^~~~~
      |         kvfree
cc1: all warnings being treated as errors
make[6]: *** [scripts/Makefile.build:229: /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.o] Error 1
make[5]: *** [/home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.12.4/Makefile:1936: /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1] Error 2
make[4]: *** [Makefile:224: __sub-make] Error 2
```

**Comment by ZqinKing** [comment]
> 求助~~
> 
> ```
> make[4]: Entering directory '/home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.12.4'
>   CC [M]  /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.o
> /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.c: In function 'nss_tunipip6_stats_read':
> /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.c:47:15: error: implicit declaration of function 'vzalloc'; did you mean 'kzalloc'? [-Werror=implicit-function-declaration]
>    47 |         buf = vzalloc(size);
>       |               ^~~~~~~
>       |               kzalloc
> /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.c:47:13: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
>    47 |         buf = vzalloc(size);
>       |             ^
> /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.c:82:9: error: implicit declaration of function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
>    82 |         vfree(buf);
>       |         ^~~~~
>       |         kvfree
> cc1: all warnings being treated as errors
> make[6]: *** [scripts/Makefile.build:229: /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tunipip6_stats.o] Error 1
> make[5]: *** [/home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.12.4/Makefile:1936: /home/etek/openwrt-LiBwrt_nss_6.12/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/qca-nss-drv-12.5.2024.04.06~53a0dc1] Error 2
> make[4]: *** [Makefile:224: __sub-make] Error 2
> ```

选的东西太多了，nss仅需保留下图所示：
![image](https://github.com/user-attachments/assets/27c77502-a713-45ce-b472-9a34f36c5733)

**Comment by jxph1123** [comment]
可以了，谢谢大佬～～
